# Exemplo de uso do bloco try-except para tratamento de erros

try:
    # Divísão por zero que causa um erro
    resultado = 10 / 0
except:
    
    print("Ocorreu um erro durante a operação!")
